from flask_init import db
from sqlalchemy.types import JSON

class Listings(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    vin = db.Column(db.String(17))
    ask_price = db.Column(db.Float)
    msrp = db.Column(db.Float)
    mileage = db.Column(db.Float)
    is_new = db.Column(db.Boolean)
    first_seen = db.Column(db.DATE)
    last_seen = db.Column(db.DATE)
    model_name = db.Column(db.String(100))
    brand_name = db.Column(db.String(100))
    year = db.Column(db.Integer)
    dealer_id = db.Column(db.Integer)
    color = db.Column(db.String(100))
    interior_color = db.Column(db.String(100))
    vin_decode = db.Column(JSON)
    horsepower = db.Column(db.Integer)
    engine_cc = db.Column(db.Integer)
    cylinders = db.Column(db.Integer)
    charger_rating = db.Column(db.Integer)


class FuelStations(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    lat_lng = db.Column(db.String(100))
    business_status = db.Column(db.String(100))
    address = db.Column(db.String(100))
    icon = db.Column(db.String(100))
    icon_background_color = db.Column(db.String(100))
    icon_mask_base_uri = db.Column(db.String(100))
    name = db.Column(db.String(100))
    open_now = db.Column(db.Boolean)
    photos = db.Column(JSON)
    place_id = db.Column(db.String(100))
    rating = db.Column(db.Float)
    user_ratings_total = db.Column(db.Integer)
    types = db.Column(JSON)
    gas_station = db.Column(db.Boolean)
    charging_station = db.Column(db.Boolean)


class Specs(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    VehiclePicture = db.Column(db.String(100))
    OverallRating = db.Column(db.String(100))
    OverallFrontCrashRating = db.Column(db.String(100))
    FrontCrashDriversideRating = db.Column(db.String(100))
    FrontCrashPassengersideRating = db.Column(db.String(100))
    FrontCrashPicture = db.Column(db.String(100))
    FrontCrashVideo = db.Column(db.String(100))
    OverallSideCrashRating = db.Column(db.String(100))
    SideCrashDriversideRating = db.Column(db.String(100))
    SideCrashPassengersideRating = db.Column(db.String(100))
    SideCrashPicture = db.Column(db.String(100))
    SideCrashVideo = db.Column(db.String(100))
    combinedSideBarrierAndPoleRatingFront = db.Column(db.String(100))
    combinedSideBarrierAndPoleRatingRear = db.Column(db.String(100))
    sideBarrierRatingOverall = db.Column(db.String(100))
    RolloverRating = db.Column(db.String(100))
    RolloverRating2 = db.Column(db.String(100))
    RolloverPossibility = db.Column(db.Float)
    RolloverPossibility2 = db.Column(db.Float)
    dynamicTipResult = db.Column(db.String(100))
    SidePoleCrashRating = db.Column(db.String(100))
    SidePolePicture = db.Column(db.String(100))
    SidePoleVideo = db.Column(db.String(100))
    NHTSAElectronicStabilityControl = db.Column(db.String(100))
    NHTSAForwardCollisionWarning = db.Column(db.String(100))
    NHTSALaneDepartureWarning = db.Column(db.String(100))
    ComplaintsCount = db.Column(db.Integer)
    RecallsCount = db.Column(db.Integer)
    InvestigationCount = db.Column(db.Integer)
    ModelYear = db.Column(db.Integer)
    Make = db.Column(db.String(100))
    Model = db.Column(db.String(100))
    VehicleDescription = db.Column(db.String(100))
    VehicleId = db.Column(db.Integer)
    complaints = db.Column(JSON)
    recalls = db.Column(JSON)
